### ISSUE TITLE
[Client] pages/main 구현

### ISSUE THREAD

**Issue by lovvp** [codestates/yeongn-client#11]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 

### TODO
1. [x] 헤더 컴포넌트 가져오기
2. [x] 섹션별 태그 작성
3. [x] 버튼에 라우터 연결하기
4. [x] 푸터 컴포넌트 가져오기
