### ISSUE TITLE
[Client] pages/appraisal/list 구현

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/yeongn-client#15]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 감정소 리스트를 카테고리별로 볼 수 있는 페이지 구현

### TODO
1. [x] 감정소 리스트 컴포넌트에서 데이터를 받아온다. 
2. [x] 카테고리 버튼 추가
3. [x] 카테고리 버튼 클릭시 데이터를 카테고리 별로 필터하는 기능 구현
4. [x] 더 보기 버튼 하단에 추가하기
