### ISSUE TITLE
[Client] pages/shop/list

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/yeongn-client#19]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 판매 리스트 글을 카테고리 별로 필터할 수 있는 페이지

### TODO
1. [x] 판매리스트 컴포넌트에서 받아온 데이터를 랜더링 한다.
2. [x] 카테고리 버튼 추가
3. [x] 카테고리 버튼 클릭시 해당 카테고리 별로 데이터를 필터.
