### ISSUE TITLE
[Client]  pages/registerSale 구현

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/yeongn-client#35]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail:  pages/registerSale 구현

### TODO
1. [x] 이미지 등록, 카테고리 컴포넌트 받아오기 
2. [x] 물품명, 판매 희망가, 물품설명 박스 만들기
3. [x] 등록 버튼시 axios 요청으로 데이터 보내기
