### ISSUE TITLE
[Client] pages/appraisal/number 구현

### ISSUE THREAD

**Issue by lovvp** [codestates/yeongn-client#39]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: appraisal 게시글 페이지 구현

### TODO
1. [x] 헤더 컴포넌트 렌더
2. [x] 게시글 데이터  컴포넌트 렌더
3. [x] 댓글 컴포넌트 렌더
