### ISSUE TITLE
[Client] components/appraisalappraisalHighPrice 구현

### ISSUE THREAD

**Issue by lovvp** [codestates/yeongn-client#41]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 게시글 데이터 컴포넌트 구현

### TODO
1. [x] 게시글 번호에 맞는 데이터  서버에 요청
2. [x] 받아온 데이터 렌더
3. [x] 좋아요 버튼 요청 만들기
4. [x] 좋아요 axios요청
5. [x] 감정가 함수 로직 만들기
6. [x] 감정하기 서버에 요청
